feat(CLAP-109): 메인페이지 구현 (진행 중)
softeerbootcamp4th/Team5-WatermelonClap-FE pull request #43
Opened 2024-08-02 01:32 UTC by thgee

## 연관된 이슈

- https://watermelon-clap.atlassian.net/browse/CLAP-109

## 작업 내용

- 메인페이지 컴포넌트 구현 완료
- 페이지에 배치 미완료 (피어세션 때문에 임시로 pr 올림)

## 리뷰어 멘션

- @DaeWon9

2024-08-02 15:52 UTC, bluejoyq requested changes
전체적으로 `style.ts`에 스타일을 모아두기로 하신건가요!? 그 이유가 궁금합니다.

2024-08-02 15:52 UTC, bluejoyq commented on packages/service/src/components/main/EventCard/EventCard.tsx
> +export const EventCard = ({ eventData }: IEventDataProps) => {
컴포넌트를 조금 더 분리해볼 수 있지 않을까요?

2024-08-02 15:52 UTC, bluejoyq commented on packages/service/src/components/main/EventCard/style.ts
> +  .title {
제 개인적인 취향이긴 한데, `css-in-js` 환경에서는 `class` 선택자를 통해 스타일링을 하기 보다는 스타일을 분리해서 적용시키는게 좋은 것 같아요. `class` 선택자보다는 변경에 덜 취약하니까요.

2024-08-02 15:52 UTC, bluejoyq commented on packages/service/src/components/main/Banner/style.ts
>  export const container = css`
파일명이 `style.ts`인 것은 컨벤션에 어긋나 보입니다.

2024-08-02 15:52 UTC, bluejoyq commented on packages/service/src/components/main/EventPeriod/Timer/Timer.tsx
> +  const { current, previous } = useMemo(() => {
`useMemo` 내부의 로직이 함수로 분리되면 좋을 것 같습니다.

2024-08-02 15:52 UTC, bluejoyq commented on packages/service/src/components/main/EventPeriod/Timer/Timer.tsx
> +const AnimatedCard = memo(
이 컴포넌트에서 `memo`를 사용하기로 결정한 이유가 궁금합니다~

2024-08-03 05:54 UTC, thgee commented on packages/service/src/components/main/Banner/style.ts
>  export const container = css`
파일명을 Banner.css.ts 라고 했을 때 실제 컴포넌트인 Banner.tsx와 헷갈려서 시도해보았습니다.
이 부분에 대해서는 팀원과 상의 후에 컨벤션을 수정해보도록 하겠습니다.

2024-08-03 06:02 UTC, thgee commented on packages/service/src/components/main/EventCard/EventCard.tsx
> +export const EventCard = ({ eventData }: IEventDataProps) => {
복잡한 로직이 있지 않다면 (단순 레이아웃이라면) 컴포넌트를 분리하지 않는 방향으로 구현해보았습니다.
그 이유는 수업시간에 크롱님이 컴포넌트를 너무 잘게 쪼개면 오히려 가독성이 떨어질 수 있다는 조언을 고려했기 때문입니다.

인라인 스타일 부분때문에 코드가 장황해보이는데, 어제 공통스타일을 더 효율적으로 사용하기 위한 회의를 진행했습니다.
회의 내용을 적용하여 더 깔끔하게 리펙토링 해보겠습니다 !

2024-08-03 06:30 UTC, thgee commented on packages/service/src/components/main/EventPeriod/Timer/Timer.tsx
> +  const { current, previous } = useMemo(() => {
Timer 컴포넌트는.. 애니메이션 예제 코드를 스타일만 커스텀 한 상태라 아직 어떻게 작동하는지 사실 잘 모르겠습니다😂
일단 뷰 완성 후에 리팩토링 기간에 최대한 분리해보도록 하겠습니다 !

2024-08-03 06:30 UTC, thgee commented on packages/service/src/components/main/EventPeriod/Timer/Timer.tsx
> +const AnimatedCard = memo(
https://github.com/softeerbootcamp4th/Team5-WatermelonClap-FE/pull/43#discussion_r1702034602

2024-08-03 06:30 UTC, thgee commented on packages/service/src/components/main/EventCard/style.ts
> +  .title {
[cc6fdba](https://github.com/softeerbootcamp4th/Team5-WatermelonClap-FE/pull/43/commits/cc6fdba3145ee1c7f9629f35c0241ed3a8976487) 수정하였습니다!

그런데 class 선택자를 통해 스타일링 했을 때 변경에 취약한 예시를 하나 보여주실 수 있으실까요??

2024-08-03 06:30 UTC, thgee commented
> 전체적으로 `style.ts`에 스타일을 모아두기로 하신건가요!? 그 이유가 궁금합니다.

[여기에서 답변 드렸습니다!](https://github.com/softeerbootcamp4th/Team5-WatermelonClap-FE/pull/43#discussion_r1702504984)

2024-08-03 16:19 UTC, bluejoyq commented on packages/service/src/components/main/EventCard/style.ts
> +  .title {
만약 class 이름이 변경된다면 스타일링도 수정해야 하는 걸 예시로 들 수 있을 것 같아요.

2024-08-03 16:20 UTC, bluejoyq approved these changes
✔️

2024-08-05 08:54 UTC, merged