chore(CLAP-124): theme depth 줄이기 및 baseStyle과 theme 통합
softeerbootcamp4th/Team5-WatermelonClap-FE pull request #45
Opened 2024-08-02 12:57 UTC by thgee

## 연관된 이슈

- https://watermelon-clap.atlassian.net/browse/CLAP-109

## 작업 내용

- 

## 리뷰어 멘션

- @DaeWon9

2024-08-02 15:44 UTC, bluejoyq requested changes

2024-08-02 15:44 UTC, bluejoyq commented on packages/core/src/theme/index.ts
> +import  from "./";
🤔

2024-08-03 05:08 UTC, thgee commented on packages/core/src/theme/index.ts
> +import  from "./";
이런.. 수정했습니다 !

2024-08-03 06:22 UTC, DaeWon9 commented on packages/core/src/theme/index.ts
> +import  from "./";
빼먹은 부분이 있었군요

2024-08-03 06:23 UTC, DaeWon9 approved these changes
뎁스도 줄고, 전체적인 길이도 줄어서 인라인에서 사용할 떄 더 직관적이고 좋아졌네요

2024-08-03 06:33 UTC, thgee commented
🔥

2024-08-03 16:21 UTC, bluejoyq approved these changes
☑️

2024-08-04 04:22 UTC, merged