feat(CLAP-134): parts-pick 페이지 API 연동
softeerbootcamp4th/Team5-WatermelonClap-FE pull request #70
Opened 2024-08-10 06:11 UTC by thgee

# 🔗 연관된 이슈

- [연관된 이슈 링크](https://watermelon-clap.atlassian.net/browse/CLAP-134?atlOrigin=eyJpIjoiYjNlZGY0ZjAwODhlNGFlMmIzYTkwNzNhODc3NDk0YjIiLCJwIjoiaiJ9)
  
<br/>

# 📗 작업 내용

### 이슈 내용
- 파츠 뽑기 이벤트 참여 시 로그인이 필요하여 로그인 플로우를 구현하였습니다.

### 변경 사항
- `파츠뽑기 이벤트 소개 페이지`에서 `지금 바로 뽑기` 버튼 클릭 시 로그인 모달을 띄웁니다.
- 로그인하지 않은 유저가 url을 입력하여 즉시 `파츠뽑기` 페이지로 이동하는 경우에도 로그인 처리를 하였습니다.

<br/>

# ✏️ 리뷰어 멘션

- @DaeWon9

2024-08-12 04:46 UTC, DaeWon9 requested changes

2024-08-12 04:46 UTC, DaeWon9 commented on packages/service/src/apis/partsEvent/apiGetPartsRemain.ts
> +    .then((data) => data);
data를 한번 더 리턴하는 이유가 있나요?

2024-08-12 04:46 UTC, DaeWon9 commented on packages/service/src/apis/partsEvent/apiPostParts.ts
> +    .then((data) => data);
여기두요

2024-08-12 04:46 UTC, DaeWon9 commented on packages/service/src/components/partsPick/PartsCard/PartsCard.tsx
> +  // frontImage,
주석은 지워주세요

2024-08-13 01:19 UTC, thgee commented on packages/service/src/apis/partsEvent/apiGetPartsRemain.ts
> +    .then((data) => data);
[수정했습니다 !](https://github.com/softeerbootcamp4th/Team5-WatermelonClap-FE/pull/70/commits/d39bd17d6bdfb4c5a98d1e30ee00f6c6618f4d2c)

2024-08-13 01:19 UTC, thgee commented on packages/service/src/apis/partsEvent/apiPostParts.ts
> +    .then((data) => data);
[수정했습니다 !](https://github.com/softeerbootcamp4th/Team5-WatermelonClap-FE/pull/70/commits/d39bd17d6bdfb4c5a98d1e30ee00f6c6618f4d2c)

2024-08-13 01:19 UTC, thgee commented on packages/service/src/components/partsPick/PartsCard/PartsCard.tsx
> +  // frontImage,
[수정했습니다 !](https://github.com/softeerbootcamp4th/Team5-WatermelonClap-FE/pull/70/commits/d39bd17d6bdfb4c5a98d1e30ee00f6c6618f4d2c)

2024-08-13 01:27 UTC, DaeWon9 approved these changes
파츠뽑기가 실제로 되니까 좋네요!, QA거치면서 버그만 좀 고치면 될거같아요!

2024-08-13 01:28 UTC, merged