feat(CLAP-33): 이미지 로드 스크린
softeerbootcamp4th/Team5-WatermelonClap-FE pull request #9
Opened 2024-07-23 10:10 UTC by DaeWon9

## 연관된 이슈
https://watermelon-clap.atlassian.net/browse/CLAP-33)

## 작업 내용
무거운 이미지들의 경우 AssetWrap로 감싸게되면 해당 이미지들이 로드된 후 페이지가 보여질 수 있도록 했어요

## 리뷰어 멘션
@bluejoyq 
@thgee 

## 스크린샷 (선택)

## 리뷰 요구사항(선택)

2024-07-23 13:03 UTC, bluejoyq requested changes

2024-07-23 13:03 UTC, bluejoyq commented on packages/service/src/common/components/AssetLoaderOverlay/AssetWrapper.tsx
> +const AssetWrapper: React.FC<AssetWrapperProps> = ({ src, alt, className }) => {
이 컴포넌트의 경우에는 주석으로 context 아래에서만 사용해야 한다고 정해주면 좋을 것 같습니다.

2024-07-23 13:03 UTC, bluejoyq commented on packages/service/src/common/components/AssetLoaderOverlay/Overlay.tsx
> +  if (state.percentage === FULL_PROGRESS) {
여기서 직접 처리하는 것 보다는 `Provider`에서 처리하는게 어떤가요?

2024-07-24 02:47 UTC, thgee commented on packages/service/src/common/contexts/AssetLoaderContext.ts
> +export const AssetLoaderContext = createContext<IAssetLoaderContext | null>(
useAssetLoader 내부에 넣지 않고 따로 분리해놓은 이유가 있나요?

2024-07-24 03:14 UTC, DaeWon9 commented on packages/service/src/common/components/AssetLoaderOverlay/Overlay.tsx
> +export default Overlay;
이름 추천해주실 수 있나요

2024-07-24 03:14 UTC, DaeWon9 commented on packages/service/src/common/contexts/AssetLoaderContext.ts
> +export enum AssetLoaderStateStatus {
할리의 의견도 동일해서 적용완료 했습니다.

2024-07-24 08:14 UTC, bluejoyq approved these changes

2024-07-24 08:14 UTC, merged